stages:
  import-ml10m:
    cmd: lenskit data convert --movielens ml-10m.zip ml-10m
    wdir: data
    deps:
      - ml-10m.zip
    outs:
      - ml-10m
  split-ml10m:
    cmd: lenskit data split --fraction 0.15 --min-train-interactions 1 ml-10m
    wdir: data
    deps:
      - ml-10m
    outs:
      - ml-10m.train
      - ml-10m.test.parquet
  # For this example, we re-split train to get validation data.
  split-ml10m-valid:
    cmd: lenskit data split --fraction 0.15 --min-train-interactions 1 -d tuning/ml-10m data/ml-10m.train
    deps:
      - data/ml-10m.train
    outs:
      - tuning/ml-10m/train
      - tuning/ml-10m/test.parquet
  tune:
    matrix:
      data:
        - ml-10m
      pipeline:
        - als
        - slim
    cmd: lenskit tune -T tuning/${item.data}/train -V tuning/${item.data}/test.parquet --save-pipeline tuning/${item.data}/${item.pipeline}.json pipelines/${item.pipeline}-search.toml tuning/${item.data}/${item.pipeline}
    deps:
      - pipelines/${item.pipeline}-search.toml
      - tuning/${item.data}/train
      - tuning/${item.data}/test.parquet
    outs:
      - tuning/${item.data}/${item.pipeline}
      - tuning/${item.data}/${item.pipeline}.json:
          cache: false
  generate:
    matrix:
      data:
        - ml-10m
      pipeline:
        - popular
        - als
        - slim
    cmd: python scripts/generate-recs.py ${item.pipeline} ${item.data}
    deps:
      - scripts/generate-recs.py
      - pipelines/${item.pipeline}.toml
      - data/${item.data}.train
      - data/${item.data}.test.parquet
    params:
      # changing random seed should change outputs
      - lenskit.toml:
          - random.seed
    outs:
      - runs/${item.data}/${item.pipeline}.recs.parquet
  report:
    cmd: jupytext --sync --execute EvalMetrics.md
    deps:
      - EvalMetrics.md
      - runs/ml-10m
    outs:
      - EvalMetrics.ipynb
  report-html:
    cmd: jupyter nbconvert --to html EvalMetrics.ipynb
    deps:
      - EvalMetrics.ipynb
    outs:
      - EvalMetrics.html
