[project]
name = "recsys26-repro1"
version = "0.1.0"
description = "Example project for RecSys reproducibility tutorial."
readme = "README.md"
requires-python = ">=3.14"
authors = [{ name = "Michael Ekstrand", email = "mdekstrand@drexel.edu" }]
dependencies = ["docopt-ng~=0.9.0", "dvc[s3,webdav]~=3.67", "lenskit~=2026.3"]

[dependency-groups]
dev = ["prek>=0.5.3", "ruff>=0.16.9", "ty>=0.0.84"]
